export enum DATA_TYPES {
  BASE64 = 'base64',
  BINARY = 'binary',
  BOOLEAN = 'boolean',
  CHAR = 'char',
  DATE = 'date',
  DOUBLE = 'double',
  ENUM = 'enum',
  FLOAT = 'float',
  INTEGER = 'int',
  JSON = 'json',
  MEDIUM_TEXT = 'mediumtext',
  TEXT = 'text',
  TIME = 'time',
  TIMESTAMP = 'timestamp',
  UUID = 'uuid',
  VARCHAR = 'varchar',
  JSONB = 'jsonb',
}
